mysql_root_password: ""
mysql_databases:
  - name: tooling
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: webaccess
    host: "%" # Webserver subnet cidr
    password: ZakirCmt$
    priv: "tooling.*:ALL"